### ISSUE TITLE
400 error even when connection works

### ISSUE THREAD

**Issue by doomsday53** [nostrenz/hatate-iqdb-tagger#17]
For some reason i keep getting a pop up giving me a 400 error when connected to the hydrus api, but I have the app, api, and access key all set up. The image processing still continues but its really annoying having that pop up every once and a while.
![unknown](https://user-images.githubusercontent.com/26168250/152222136-012a798f-cd19-4cee-8ee4-119f325fcd4d.png)
.

**Comment by nostrenz** [comment]
Hi,

I'm not sure what's happening here, I'll need to investigate this as I've never seen this window appearing during normal use with the API set up and Hydrus running. What version of Hydrus are you running? Could be due to Hatate making requests not supported by an older or newer version of the API.

**Comment by doomsday53** [comment]
> 

I’m using the most up to date version of hydrus so that might be it.

**Comment by JKammder27** [comment]
For me it just won't send the files automatically to Hydrus when it previously did

**Comment by nostrenz** [comment]
Sorry for the wait, I think this problem is due to an invalid Hydrus tag service being selected in the settings.
If that's the case, opening the "Settings" > "Hydrus API" window and selecting the tag service again should fix the problem. I've added some wording to the "400 Bad Request" window about this problem in the last release.

**Comment by vickyorlo** [comment]
Have a similar problem (on wine, though). Tried to set the tag service multiple times, made sure it's selected, still getting 400s.

**Comment by KamillaPup** [comment]
I wonder if this is related to #25
